// {
//     meals: [
//         {
//             idMeal: "52807",
//             strMeal: "Baingan Bharta",
//             strDrinkAlternate: null,
//             strCategory: "Vegetarian",
//             strArea: "Indian",
//             strInstructions: "Rinse the baingan (eggplant or aubergine) in water. Pat dry with a kitchen napkin. Apply some oil all over and keep it for roasting on an open flame. You can also grill the baingan or roast in the oven. But then you won't get the smoky flavor of the baingan. Keep the eggplant turning after a 2 to 3 minutes on the flame, so that its evenly cooked. You could also embed some garlic cloves in the baingan and then roast it. 2. Roast the aubergine till its completely cooked and tender. With a knife check the doneness. The knife should slid easily in aubergines without any resistance. Remove the baingan and immerse in a bowl of water till it cools down. 3. You can also do the dhungar technique of infusing charcoal smoky flavor in the baingan. This is an optional step. Use natural charcoal for this method. Heat a small piece of charcoal on flame till it becomes smoking hot and red. 4. Make small cuts on the baingan with a knife. Place the red hot charcoal in the same plate where the roasted aubergine is kept. Add a few drops of oil on the charcoal. The charcoal would begin to smoke. 5. As soon as smoke begins to release from the charcoal, cover the entire plate tightly with a large bowl. Allow the charcoal smoke to get infused for 1 to 2 minutes. The more you do, the more smoky the baingan bharta will become. I just keep for a minute. Alternatively, you can also do this dhungar method once the baingan bharta is cooked, just like the way we do for Dal Tadka. 6. Peel the skin from the roasted and smoked eggplant. 7. Chop the cooked eggplant finely or you can even mash it. 8. In a kadai or pan, heat oil. Then add finely chopped onions and garlic. 9. Saute the onions till translucent. Don't brown them. 10. Add chopped green chilies and saute for a minute. 11. Add the chopped tomatoes and mix it well. 12. Bhuno (saute) the tomatoes till the oil starts separating from the mixture. 13. Now add the red chili powder. Stir and mix well. 14. Add the chopped cooked baingan. 15. Stir and mix the chopped baingan very well with the onion­tomato masala mixture. 16. Season with salt. Stir and saute for some more 4 to 5 minutes more. 17. Finally stir in the coriander leaves with the baingan bharta or garnish it with them. Serve Baingan Bharta with phulkas, rotis or chapatis. It goes well even with bread, toasted or grilled bread and plain rice or jeera rice.",
//             strMealThumb: "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
//             strTags: "Spicy,Bun,Calorific",
//             strYoutube: "https://www.youtube.com/watch?v=-84Zz2EP4h4",
//             strIngredient1: "Aubergine",
//             strIngredient2: "Onion",
//             strIngredient3: "Tomatoes",
//             strIngredient4: "Garlic",
//             strIngredient5: "Green Chili",
//             strIngredient6: "Red Chili Powder",
//             strIngredient7: "Oil",
//             strIngredient8: "Coriander Leaves",
//             strIngredient9: "salt",
//             strIngredient10: "",
//             strIngredient11: "",
//             strIngredient12: "",
//             strIngredient13: "",
//             strIngredient14: "",
//             strIngredient15: "",
//             strIngredient16: "",
//             strIngredient17: "",
//             strIngredient18: "",
//             strIngredient19: "",
//             strIngredient20: "",
//             strMeasure1: "1 large",
//             strMeasure2: "½ cup ",
//             strMeasure3: "1 cup",
//             strMeasure4: "6 cloves",
//             strMeasure5: "1",
//             strMeasure6: "¼ teaspoon",
//             strMeasure7: "1.5 tablespoon",
//             strMeasure8: "1 tablespoon chopped",
//             strMeasure9: "as required",
//             strMeasure10: "",
//             strMeasure11: "",
//             strMeasure12: "",
//             strMeasure13: "",
//             strMeasure14: "",
//             strMeasure15: "",
//             strMeasure16: "",
//             strMeasure17: "",
//             strMeasure18: "",
//             strMeasure19: "",
//             strMeasure20: "",
//             strSource: "http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/",
//             dateModified: null
//         }
//     ]
// }

export const localRecipesTheMealDb = {
    meals:
        [
            {
                idMeal: "52807",
                strMeal: "Baingan Bharta",
                strMealThumb: "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
                strIngredient1: "Aubergine",
                strIngredient2: "Onion",
                strIngredient3: "Tomatoes",
                strIngredient4: "Garlic",
                strIngredient5: "",
                strMeasure1: "1 large",
                strMeasure2: "½ cup ",
                strMeasure3: "1 cup",
                strMeasure4: "6 cloves",
                strMeasure5: "",
                strSource: "http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/"
            },
            {
                idMeal: "52785",
                strMeal: "Dal fry",
                strMealThumb: "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
                strIngredient1: "Toor dal",
                strIngredient2: "Water",
                strIngredient3: "Salt",
                strIngredient4: "",
                strMeasure1: "1 cup",
                strMeasure2: "2-1/2 cups",
                strMeasure3: "as required",
                strMeasure4: "",
                strSource: "https://www.instagram.com/p/BO21bpYD3Fu"
            },
            {
                idMeal: "52868",
                strMeal: "Kidney Bean Curry",
                strMealThumb: "https://www.themealdb.com/images/media/meals/sywrsu1511463066.jpg",
                strIngredient1: "Vegetable Oil",
                strIngredient2: "Onion",
                strIngredient3: "Garlic",
                strIngredient4: "Basmati Rice",
                strIngredient5: "",
                strMeasure1: "1 tbls",
                strMeasure2: "1 finely chopped ",
                strMeasure3: "2 cloves chopped",
                strMeasure4: "to serve",
                strMeasure5: "",
                strSource: "https://www.bbcgoodfood.com/recipes/kidney-bean-curry"
            },
            {
                idMeal: "52807",
                strMeal: "Baingan Bharta",
                strMealThumb: "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
                strIngredient1: "Aubergine",
                strIngredient2: "Onion",
                strIngredient3: "Tomatoes",
                strIngredient4: "Garlic",
                strIngredient5: "",
                strMeasure1: "1 large",
                strMeasure2: "½ cup ",
                strMeasure3: "1 cup",
                strMeasure4: "6 cloves",
                strMeasure5: "",
                strSource: "http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/"
            },
            {
                idMeal: "52785",
                strMeal: "Dal fry",
                strMealThumb: "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
                strIngredient1: "Toor dal",
                strIngredient2: "Water",
                strIngredient3: "Salt",
                strIngredient4: "",
                strMeasure1: "1 cup",
                strMeasure2: "2-1/2 cups",
                strMeasure3: "as required",
                strMeasure4: "",
                strSource: "https://www.instagram.com/p/BO21bpYD3Fu"
            },
            {
                idMeal: "52868",
                strMeal: "Kidney Bean Curry",
                strMealThumb: "https://www.themealdb.com/images/media/meals/sywrsu1511463066.jpg",
                strIngredient1: "Vegetable Oil",
                strIngredient2: "Onion",
                strIngredient3: "Garlic",
                strIngredient4: "Basmati Rice",
                strIngredient5: "",
                strMeasure1: "1 tbls",
                strMeasure2: "1 finely chopped ",
                strMeasure3: "2 cloves chopped",
                strMeasure4: "to serve",
                strMeasure5: "",
                strSource: "https://www.bbcgoodfood.com/recipes/kidney-bean-curry"
            },
            {
                idMeal: "52807",
                strMeal: "Baingan Bharta",
                strMealThumb: "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
                strIngredient1: "Aubergine",
                strIngredient2: "Onion",
                strIngredient3: "Tomatoes",
                strIngredient4: "Garlic",
                strIngredient5: "",
                strMeasure1: "1 large",
                strMeasure2: "½ cup ",
                strMeasure3: "1 cup",
                strMeasure4: "6 cloves",
                strMeasure5: "",
                strSource: "http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/"
            },
            {
                idMeal: "52785",
                strMeal: "Dal fry",
                strMealThumb: "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
                strIngredient1: "Toor dal",
                strIngredient2: "Water",
                strIngredient3: "Salt",
                strIngredient4: "",
                strMeasure1: "1 cup",
                strMeasure2: "2-1/2 cups",
                strMeasure3: "as required",
                strMeasure4: "",
                strSource: "https://www.instagram.com/p/BO21bpYD3Fu"
            },
            {
                idMeal: "52868",
                strMeal: "Kidney Bean Curry",
                strMealThumb: "https://www.themealdb.com/images/media/meals/sywrsu1511463066.jpg",
                strIngredient1: "Vegetable Oil",
                strIngredient2: "Onion",
                strIngredient3: "Garlic",
                strIngredient4: "Basmati Rice",
                strIngredient5: "",
                strMeasure1: "1 tbls",
                strMeasure2: "1 finely chopped ",
                strMeasure3: "2 cloves chopped",
                strMeasure4: "to serve",
                strMeasure5: "",
                strSource: "https://www.bbcgoodfood.com/recipes/kidney-bean-curry"
            },
            {
                idMeal: "52807",
                strMeal: "Baingan Bharta",
                strMealThumb: "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
                strIngredient1: "Aubergine",
                strIngredient2: "Onion",
                strIngredient3: "Tomatoes",
                strIngredient4: "Garlic",
                strIngredient5: "",
                strMeasure1: "1 large",
                strMeasure2: "½ cup ",
                strMeasure3: "1 cup",
                strMeasure4: "6 cloves",
                strMeasure5: "",
                strSource: "http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/"
            },
            {
                idMeal: "52785",
                strMeal: "Dal fry",
                strMealThumb: "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
                strIngredient1: "Toor dal",
                strIngredient2: "Water",
                strIngredient3: "Salt",
                strIngredient4: "",
                strMeasure1: "1 cup",
                strMeasure2: "2-1/2 cups",
                strMeasure3: "as required",
                strMeasure4: "",
                strSource: "https://www.instagram.com/p/BO21bpYD3Fu"
            },
            {
                idMeal: "52868",
                strMeal: "Kidney Bean Curry",
                strMealThumb: "https://www.themealdb.com/images/media/meals/sywrsu1511463066.jpg",
                strIngredient1: "Vegetable Oil",
                strIngredient2: "Onion",
                strIngredient3: "Garlic",
                strIngredient4: "Basmati Rice",
                strIngredient5: "",
                strMeasure1: "1 tbls",
                strMeasure2: "1 finely chopped ",
                strMeasure3: "2 cloves chopped",
                strMeasure4: "to serve",
                strMeasure5: "",
                strSource: "https://www.bbcgoodfood.com/recipes/kidney-bean-curry"
            },
            {
                idMeal: "52807",
                strMeal: "Baingan Bharta",
                strMealThumb: "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
                strIngredient1: "Aubergine",
                strIngredient2: "Onion",
                strIngredient3: "Tomatoes",
                strIngredient4: "Garlic",
                strIngredient5: "",
                strMeasure1: "1 large",
                strMeasure2: "½ cup ",
                strMeasure3: "1 cup",
                strMeasure4: "6 cloves",
                strMeasure5: "",
                strSource: "http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/"
            },
            {
                idMeal: "52785",
                strMeal: "Dal fry",
                strMealThumb: "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
                strIngredient1: "Toor dal",
                strIngredient2: "Water",
                strIngredient3: "Salt",
                strIngredient4: "",
                strMeasure1: "1 cup",
                strMeasure2: "2-1/2 cups",
                strMeasure3: "as required",
                strMeasure4: "",
                strSource: "https://www.instagram.com/p/BO21bpYD3Fu"
            },
            {
                idMeal: "52868",
                strMeal: "Kidney Bean Curry",
                strMealThumb: "https://www.themealdb.com/images/media/meals/sywrsu1511463066.jpg",
                strIngredient1: "Vegetable Oil",
                strIngredient2: "Onion",
                strIngredient3: "Garlic",
                strIngredient4: "Basmati Rice",
                strIngredient5: "",
                strMeasure1: "1 tbls",
                strMeasure2: "1 finely chopped ",
                strMeasure3: "2 cloves chopped",
                strMeasure4: "to serve",
                strMeasure5: "",
                strSource: "https://www.bbcgoodfood.com/recipes/kidney-bean-curry"
            },
            {
                idMeal: "52807",
                strMeal: "Baingan Bharta",
                strMealThumb: "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
                strIngredient1: "Aubergine",
                strIngredient2: "Onion",
                strIngredient3: "Tomatoes",
                strIngredient4: "Garlic",
                strIngredient5: "",
                strMeasure1: "1 large",
                strMeasure2: "½ cup ",
                strMeasure3: "1 cup",
                strMeasure4: "6 cloves",
                strMeasure5: "",
                strSource: "http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/"
            },
            {
                idMeal: "52785",
                strMeal: "Dal fry",
                strMealThumb: "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
                strIngredient1: "Toor dal",
                strIngredient2: "Water",
                strIngredient3: "Salt",
                strIngredient4: "",
                strMeasure1: "1 cup",
                strMeasure2: "2-1/2 cups",
                strMeasure3: "as required",
                strMeasure4: "",
                strSource: "https://www.instagram.com/p/BO21bpYD3Fu"
            },
            {
                idMeal: "52868",
                strMeal: "Kidney Bean Curry",
                strMealThumb: "https://www.themealdb.com/images/media/meals/sywrsu1511463066.jpg",
                strIngredient1: "Vegetable Oil",
                strIngredient2: "Onion",
                strIngredient3: "Garlic",
                strIngredient4: "Basmati Rice",
                strIngredient5: "",
                strMeasure1: "1 tbls",
                strMeasure2: "1 finely chopped ",
                strMeasure3: "2 cloves chopped",
                strMeasure4: "to serve",
                strMeasure5: "",
                strSource: "https://www.bbcgoodfood.com/recipes/kidney-bean-curry"
            }
        ]
};

export const localRecipesFoodToFork = [{
    recipe_id: '100',
    title: 'Farm House Pizza Dough',
    image_url: './img/test-1.jpg',
    publisher: 'Jungle',
    source_url: './img/test-1.jpg',
    ingredients: ['1 pounds Ground Coffee (good, Rich Roast)', '1 can tuna packed in olive oil']
},
{
    recipe_id: '101',
    title: 'Margarita Pizza Dough',
    image_url: './img/test-2.jpg',
    publisher: 'Rita',
    source_url: './img/test-2.jpg',
    ingredients: ['1/2 cup jack and cheddar cheese, shredded', '8 quarts Cold Water']
},
{
    recipe_id: '102',
    title: 'Burger Pizza',
    image_url: './img/test-3.jpg',
    publisher: 'P Burger',
    source_url: './img/test-3.jpg',
    ingredients: ['1000 g pasta', '1000 grams pasta']
},
{
    recipe_id: '103',
    title: 'Veg Munchurian Sizzeler Pizza',
    image_url: './img/test-4.jpg',
    publisher: 'Pacific',
    source_url: './img/test-4.jpg',
    ingredients: ['1000 g pasta', '1 tablespoons butter, room temperature']
},
{
    recipe_id: '104',
    title: 'Belgium Choco',
    image_url: './img/test-5.jpg',
    publisher: 'Bel Choco',
    source_url: './img/test-5.jpg',
    ingredients: ['1000 g pasta', '1 can tuna packed in olive oil']
},
{
    recipe_id: '105',
    title: 'Masala Dosa With Sambh Rice',
    image_url: './img/test-6.jpg',
    publisher: 'South',
    source_url: './img/test-6.jpg',
    ingredients: ['1000 g pasta', '1 can tuna packed in olive oil']
},
{
    recipe_id: '106',
    title: 'Soya Rolls with Spice Chatnee Special',
    image_url: './img/test-7.jpg',
    publisher: 'Chorangi Lane',
    source_url: './img/test-7.jpg',
    ingredients: ['1000 g pasta', '1 can tuna packed in olive oil']
},
{
    recipe_id: '107',
    title: 'Gol Gol Jalebi with Rashmalai',
    image_url: './img/test-8.jpg',
    publisher: 'Jalebi',
    source_url: './img/test-8.jpg',
    ingredients: ['1000 g pasta', '1 can tuna packed in olive oil']
},
{
    recipe_id: '108',
    title: 'Veg Chowmine without Mirchee',
    image_url: './img/test-9.jpg',
    publisher: 'Mahadeva',
    source_url: './img/test-9.jpg',
    ingredients: ['1000 g pasta', '1 can tuna packed in olive oil']
},
{
    recipe_id: '109',
    title: 'Haldiram Patisha and Rajan Patisha',
    image_url: './img/test-10.jpg',
    publisher: 'Rajan Palam Wale',
    source_url: './img/test-10.jpg',
    ingredients: ['1000 g pasta', '1 can tuna packed in olive oil']
}
];